// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odnnrqjddkxbxstxyleu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kbm5ycWpkZGt4YnhzdHh5bGV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzQ2NzEsImV4cCI6MjA2OTg1MDY3MX0.JJuHl-Ollbf-5DQdRg9HyL0aW3m7dlGRn87OErNaROs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});